// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gorm_gen

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFile = "pre_files"

// File mapped from table <pre_files>
type File struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Pid       int64          `gorm:"column:pid;comment:上级ID" json:"pid"`              // 上级ID
	Pids      string         `gorm:"column:pids;comment:上级ID递归" json:"pids"`          // 上级ID递归
	Cid       int64          `gorm:"column:cid;comment:复制ID" json:"cid"`              // 复制ID
	Name      string         `gorm:"column:name;comment:名称" json:"name"`              // 名称
	Type      string         `gorm:"column:type;comment:类型" json:"type"`              // 类型
	Ext       string         `gorm:"column:ext;comment:后缀名" json:"ext"`               // 后缀名
	Size      int64          `gorm:"column:size;comment:大小(B)" json:"size"`           // 大小(B)
	Userid    int64          `gorm:"column:userid;comment:拥有者ID" json:"userid"`       // 拥有者ID
	Share     int32          `gorm:"column:share;comment:是否共享" json:"share"`          // 是否共享
	Pshare    int64          `gorm:"column:pshare;comment:所属分享ID" json:"pshare"`      // 所属分享ID
	CreatedID int64          `gorm:"column:created_id;comment:创建者" json:"created_id"` // 创建者
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
