// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gorm_gen

import (
	"time"
)

const TableNameFile_User = "pre_file_users"

// File_User mapped from table <pre_file_users>
type File_User struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FileID     int64     `gorm:"column:file_id;comment:项目ID" json:"file_id"`             // 项目ID
	Userid     int64     `gorm:"column:userid;comment:成员ID" json:"userid"`               // 成员ID
	Permission int32     `gorm:"column:permission;comment:权限：0只读，1读写" json:"permission"` // 权限：0只读，1读写
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName File_User's table name
func (*File_User) TableName() string {
	return TableNameFile_User
}
