// Code generated by hertz generator.

package txyun

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _contentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _officeuploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _saveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}
