// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	aliyun "github.com/cloudisk/biz/router/aliyun"
	//qiniuyun "github.com/cloudisk/biz/router/qiniuyun"
	//txyun "github.com/cloudisk/biz/router/txyun"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	//qiniuyun.Register(r)

	//txyun.Register(r)

	aliyun.Register(r)
}
